name: Default CI pipeline
on: 
  workflow_call: 
    inputs:
      node_version: 
        required: true
        type: string
      cache_type: 
        required: true
        type: string 
    secrets: 
      database_url:
        required: true

jobs: 
  ci-verification: 
    runs-on: ubuntu-latest
    steps: 
      - name: Git Repository Checkout
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Node Js Setup 
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ inputs.node_version }}
          cache: ${{ inputs.cache_type }}

      - name: Dependencies installing
        run: npm ci

      - name: Prisma Generate
        run: npx prisma generate --schema=./src/database/prisma/schema.prisma
        env: 
          DATABASE_URL: ${{ secrets.database_url }} 

      - name: Codebase Linting and formatting
        uses: wearerequired/lint-action@v2
        with: 
          eslint: true
          prettier: true

      - name: Application building
        run: npm run build

      - name: Application test
        run: npm run test 

      - name: Application test coverage
        run: npm run test:cov
